services:
  konseling-hub-postgres:
    container_name: konseling-hub-postgres
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
      - POSTGRES_USER=user

  konseling-hub-redis:
    container_name: konseling-hub-redis
    image: redis:6
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf

  konseling-hub-api:
    build:
      context: ./konseling-hub-api
      dockerfile: Dockerfile
    depends_on:
      - konseling-hub-postgres
      - konseling-hub-redis
    image: konseling-hub-api:1.0.0
    container_name: konseling-hub-api
    environment:
      - APP_PORT=9000
    ports:
      - 9000:9000
    command: sh -c "until nc -z konseling-hub-postgres 5432 && nc -z konseling-hub-redis 6379; do echo 'Waiting for konseling-hub-postgres and konseling-hub-redis'; sleep 1; done; npm run build; npm start;"

  konseling-hub-hub:
    build:
      context: ./konseling-hub
      dockerfile: Dockerfile
    depends_on:
      - konseling-hub-api
    image: konseling-hub:1.0.0
    container_name: konseling-hub
    ports:
      - 3000:3000
    command: sh -c "until nc -z konseling-hub-api 9000; do echo 'Waiting for konseling-hub-api'; sleep 1; done; npm run build; npm start;"
