services:
  konseling-hub-postgres:
    container_name: konseling-hub-postgres
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=KonselingHub2024
      - POSTGRES_DB=konseling-hub
      - POSTGRES_USER=konseling-hub-user

  konseling-hub-redis:
    container_name: konseling-hub-redis
    image: redis:6
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf

  konseling-hub-api:
    build:
      context: ./konseling-hub-api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://konseling-hub-user:KonselingHub2024@konseling-hub-postgres:5432/konseling-hub?schema=public
      - ALLOWED_ORIGIN=["https://www.konseling-hub.com","https://konseling-hub.com"]
      - REDIS_HOST=konseling-hub-redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=konseling-hub-user
      - REDIS_PASSWORD=KonselingHub2024
      - ACCESS_TOKEN_SECRET="jwt-access-token-key"
      - REFRESH_TOKEN_SECRET="jwt-refresh-token-key"
      - IS_HTTPS=true

    depends_on:
      - konseling-hub-postgres
      - konseling-hub-redis
    image: konseling-hub-api:1.0.0-beta
    container_name: konseling-hub-api
    ports:
      - 9000:9000
    command: sh -c "npx prisma migrate deploy; npx prisma db seed; npm start"

  konseling-hub-app:
    build:
      context: ./konseling-hub-app
      dockerfile: Dockerfile
      args:
        - API_ORIGIN=https://www.api-konseling-hub.com
        - IS_HTTPS=true
        - APP_ORIGIN=https://www.konseling-hub.com
    depends_on:
      - konseling-hub-api
    image: konseling-hub-app:1.0.0-beta
    container_name: konseling-hub-app
    ports:
      - 3000:3000
