services:
  counselinghub-postgres:
    container_name: counselinghub-postgres
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=counselinghub2024
      - POSTGRES_DB=counselinghub
      - POSTGRES_USER=counselinghub-user

  counselinghub-redis:
    container_name: counselinghub-redis
    image: redis:6
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf

  counselinghub-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://counselinghub-user:counselinghub2024@counselinghub-postgres:5432/counselinghub?schema=public
      - ALLOWED_ORIGIN=["https://www.counselinghub.com","https://counselinghub.com"]
      - REDIS_HOST=counselinghub-redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=counselinghub-user
      - REDIS_PASSWORD=counselinghub2024
      - ACCESS_TOKEN_SECRET="jwt-access-token-key"
      - REFRESH_TOKEN_SECRET="jwt-refresh-token-key"
      - IS_HTTPS=true
      - APP_ORIGIN=https://www.api-counselinghub.com

    depends_on:
      - counselinghub-postgres
      - counselinghub-redis
    image: counselinghub-api:1.0.0-beta
    container_name: counselinghub-api
    ports:
      - 9000:9000
    command: sh -c "npx prisma migrate deploy; npx prisma db seed; npm start"

  counselinghub-app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - API_ORIGIN=https://www.counselinghub-api.com
        - IS_HTTPS=true
    environment:
      - ALLOWED_ORIGINS=["*counselinghub-app.com"]
    depends_on:
      - counselinghub-api
    image: counselinghub-app:1.0.0-beta
    container_name: counselinghub-app
    ports:
      - 3000:3000
